import inquirer from "inquirer";
import path from "path";
import { run, deleteFolder, createFolder, deleteFile, fileExists, writeFile } from './lib/utils.js';
import { createPages } from './lib/templates.js';
import { readFileSync } from 'fs';

(async () => {
    const answers = await inquirer.prompt([
        {
            type: "input",
            name: "projectName",
            message: "Enter project name:"
        },
        {
            type: "confirm",
            name: "useTypeScript",
            message: "Do you want to use TypeScript? (default: Yes)",
            default: true
        },
        {
            type: "confirm",
            name: "useTailwind",
            message: "Do you want to use Tailwind CSS? (default: Yes)",
            default: true
        },
        {
            type: "confirm",
            name: "useAppDir",
            message: "Do you want to use the app directory? (default: Yes)",
            default: true
        },
        {
            type: "input",
            name: "pages",
            message: "Enter the names of the pages you want to create (comma-separated, default: none):",
            default: "",
            filter: (input) => input.split(',').map((page) => page.trim()).filter(page => page !== '')
        },
        {
            type: "list",
            name: "linter",
            message: "Choose a linter (default: none):",
            choices: ["none", "eslint", "biome"],
            default: "none"
        },
        {
            type: "confirm",
            name: "useShadcn",
            message: "Do you want to use Shadcn UI? (default: No)",
            default: false
        }
    ]);

    const { projectName, useTypeScript, useTailwind, useAppDir, pages, linter, useShadcn } = answers;
    const projectPath = path.join(process.cwd(), projectName);

    console.log(`
        Creating ${projectName}...`);

    let command = `npx create-next-app@latest ${projectName} --use-npm --yes`;
    if (useTypeScript) {
        command += " --ts";
    } else {
        command += " --js";
    }
    if (useTailwind) {
        command += " --tailwind";
    }
    if (useAppDir) {
        command += " --app";
    } else {
        command += " --no-app --src-dir";
    }

    if (linter === "none") {
        command += " --no-eslint";
    }

    run(command);

    const publicPath = path.join(projectPath, "public");
    deleteFolder(publicPath);
    createFolder(publicPath);

    if (useAppDir) {
        const layoutPath = path.join(projectPath, "app", useTypeScript ? "layout.tsx" : "layout.jsx");
        if (fileExists(layoutPath)) {
            let layoutContent = readFileSync(layoutPath, "utf8");
            layoutContent = layoutContent.replace(/title: "Create Next App"/, `title: "${projectName}"`);
            layoutContent = layoutContent.replace(/description: "Generated by create next app"/, `description: ""`);
            writeFile(layoutPath, layoutContent);
        }
    }

    const pagesPath = useAppDir ? path.join(projectPath, "app") : path.join(projectPath, "src", "pages");
    createPages(pagesPath, pages, useTypeScript, useAppDir);

    const faviconPathInAppOrSrc = useAppDir ? path.join(projectPath, "app", "favicon.ico") : path.join(projectPath, "src", "favicon.ico");
    if (fileExists(faviconPathInAppOrSrc)) {
        deleteFile(faviconPathInAppOrSrc);
    }

    let defaultPagePath;
    if (useAppDir) {
        defaultPagePath = path.join(projectPath, "app", useTypeScript ? "page.tsx" : "page.jsx");
    } else {
        defaultPagePath = path.join(projectPath, "src", "pages", useTypeScript ? "index.tsx" : "index.jsx");
    }
    const emptyPageContent = 
    `export default function Page() {\n  return (\n    <></>\n  );\n}\n`;
    writeFile(defaultPagePath, emptyPageContent);

    const readmePath = path.join(projectPath, "README.md");
    writeFile(readmePath, "");

    if (linter === "biome") {
        run(`npm install --save-dev @biomejs/biome`, projectPath);
        run(`npx @biomejs/biome init`, projectPath);
    }

    if (useShadcn) {
        run(`npm install --save-dev tailwindcss-animate class-variance-authority`, projectPath);
        run(`npx shadcn@latest init`, projectPath);
        const componentsJsonPath = path.join(projectPath, "components.json");
        const componentsJsonContent = {
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": useAppDir,
            "tsx": useTypeScript,
            "tailwind": {
                "config": useTypeScript ? "tailwind.config.ts" : "tailwind.config.js",
                "css": useAppDir ? "src/app/globals.css" : "src/styles/globals.css",
                "baseColor": "slate",
                "cssVariables": true
            },
            "aliases": {
                "components": "@/components",
                "utils": "@/lib/utils"
            }
        };
        writeFile(componentsJsonPath, JSON.stringify(componentsJsonContent, null, 2));
    }

    console.log("Setup complete!");
    console.log(`
        Next steps:
        cd ${projectName}
        npm run dev`);
})();
